// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiceqOXGX_X1mim1uDbav6SHgmV3xPPTg',
    appId: '1:976619002530:web:632c2c3d820ef74cc195fb',
    messagingSenderId: '976619002530',
    projectId: 'ventas-505c8',
    authDomain: 'ventas-505c8.firebaseapp.com',
    storageBucket: 'ventas-505c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfZ5iIVHmBfQVMv1fWfxu0vRnpR_md1A',
    appId: '1:976619002530:android:b2a13c982adf79e0c195fb',
    messagingSenderId: '976619002530',
    projectId: 'ventas-505c8',
    storageBucket: 'ventas-505c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJCKUlsGYXC2kb9q0ssBm3HUqHdMR79Xk',
    appId: '1:976619002530:ios:d112b0d2e838579cc195fb',
    messagingSenderId: '976619002530',
    projectId: 'ventas-505c8',
    storageBucket: 'ventas-505c8.firebasestorage.app',
    iosBundleId: 'com.example.controlStockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJCKUlsGYXC2kb9q0ssBm3HUqHdMR79Xk',
    appId: '1:976619002530:ios:d112b0d2e838579cc195fb',
    messagingSenderId: '976619002530',
    projectId: 'ventas-505c8',
    storageBucket: 'ventas-505c8.firebasestorage.app',
    iosBundleId: 'com.example.controlStockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiceqOXGX_X1mim1uDbav6SHgmV3xPPTg',
    appId: '1:976619002530:web:632c2c3d820ef74cc195fb',
    messagingSenderId: '976619002530',
    projectId: 'ventas-505c8',
    authDomain: 'ventas-505c8.firebaseapp.com',
    storageBucket: 'ventas-505c8.firebasestorage.app',
  );

}